# Generated by Django 4.1 on 2022-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs_app", "0004_remove_blogpostmodel_image_uploadimagemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadCSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv/")),
            ],
        ),
    ]
