# Generated by Django 4.1 on 2022-10-31 09:57

import blogs_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs_app", "0006_alter_blogpostmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpostmodel",
            options={
                "permissions": (
                    ("can_post_blogpost", "can post blogpost"),
                    ("can_delete_blogpost", "can delete blogpost"),
                ),
                "verbose_name": "blog",
                "verbose_name_plural": "blogs",
            },
        ),
        migrations.AlterField(
            model_name="blogpostmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=models.SET(blogs_app.models.get_sentinel_user),
                related_name="Author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.CreateModel(
            name="CommentaryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_body", models.TextField(verbose_name="body of comment")),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "date_changed",
                    models.DateField(auto_now=True, verbose_name="Change date"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=models.SET(blogs_app.models.get_sentinel_user),
                        related_name="Commentary",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "blogpost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Commentary",
                        to="blogs_app.blogpostmodel",
                        verbose_name="blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "commentary",
                "verbose_name_plural": "commentaries",
                "permissions": (
                    ("can_post_comment", "can post comment"),
                    ("can_delete_comment", "can delete comment"),
                ),
            },
        ),
    ]
