# Generated by Django 4.1 on 2022-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs_app", "0007_alter_blogpostmodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("contents", models.TextField(verbose_name="Contents")),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
    ]
