# Generated by Django 4.1 on 2022-11-10 07:36

import blogs_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs_app", "0008_postmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostModel",
        ),
        migrations.AlterField(
            model_name="blogpostmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=models.SET(blogs_app.models.get_sentinel_user),
                related_name="blogposts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="commentarymodel",
            name="author",
            field=models.ForeignKey(
                on_delete=models.SET(blogs_app.models.get_sentinel_user),
                related_name="commentary",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="commentarymodel",
            name="blogpost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary",
                to="blogs_app.blogpostmodel",
                verbose_name="blogpost",
            ),
        ),
    ]
