# Generated by Django 4.1 on 2023-10-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogs_app", "0009_delete_postmodel_alter_blogpostmodel_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadimagemodel",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="blogs_app.blogpostmodel",
            ),
        ),
    ]
