# Generated by Django 4.1 on 2022-09-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs_app", "0002_alter_blogpostmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Автор",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
