# Generated by Django 4.1 on 2022-09-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs_app", "0003_alter_blogpostmodel_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostmodel",
            name="image",
        ),
        migrations.CreateModel(
            name="UploadImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="files/")),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Файлы",
                        to="blogs_app.blogpostmodel",
                    ),
                ),
            ],
        ),
    ]
